# .github/workflows/ci.yml
name: ci

on: [push, pull_request]

jobs:
  ci:
    uses: catalyst/catalyst-moodle-workflows/.github/workflows/ci.yml@main
    with:
      extra_plugin_runners: 'moodle-plugin-ci add-plugin --branch MOODLE_39_STABLE_catalyst catalyst/moodle-tool_lifecycle'

